### ISSUE TITLE
Envoy integration stopped working at April 12th [BUG] 

### ISSUE THREAD

**Issue by HABO7405** [vincentwolsink/home_assistant_enphase_envoy_installer#119]
**Describe the bug**
Envoy doesn't report solar panel power production since April 12th. The sensors are unavailable: Integration seems to be not working.

**Account type**
- [ ] Installer
- [ ] DIY / DHZ
- [x] Home Owner (This integration is not (fully) functional with a home owner account!)

**Envoy**
<I don't know: how to determine this?>
- [ ] Metered with CTs installed
- [ ] Metered without CTs
- [ ] Standard

- FW version: 7.6.175
- Amount of micro inverters connected: 16

**Home Assistant**
- Core: 2024.4.3
- Supervisor: 2024.04.0
- Operating System: 12.2
- Frontend: 20240404.2

**Additional context**
Sensors are not available:
<img width="649" alt="image" src="https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/assets/164520134/351a2c04-2084-4ca5-8e9c-78daf10374bb">

<img width="995" alt="image" src="https://github.com/vincentwolsink/home_assistant_enphase_envoy_installer/assets/164520134/c617e67f-ba20-406d-a338-aa5836215759">

Relevant snippet of Home Assistant error log:

2024-04-12 13:51:20.585 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Envoy 122241087305 for enphase_envoy
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/enphase_envoy/__init__.py", line 78, in async_setup_entry
enlighten_serial_num=config[CONF_SERIAL],
~~~~~~^^^^^^^^^^^^^
KeyError: 'serial'

...

2024-04-15 08:17:39.501 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Envoy 122241087305 for enphase_envoy
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/enphase_envoy/__init__.py", line 78, in async_setup_entry
enlighten_serial_num=config[CONF_SERIAL],
~~~~~~^^^^^^^^^^^^^
KeyError: 'serial'

**Comment by HABO7405** [comment]
That worked, thanks!  
Nothing changed on the Envoy.
I usually perform updates when HA provides an update: I don't remember if I updated exactly that day/time.
Around that time I installed Nordpool day-ahead-prices according to smart-home-junkie's video.
