### ISSUE TITLE
[BUG] After entering credentials I get an "Unexpected Error"

### ISSUE THREAD

**Issue by jeangroen** [vincentwolsink/home_assistant_enphase_envoy_installer#140]
**Describe the bug**
After entering credentials I get an "Unexpected Error"

**Account type**
- [ ] Installer
- [ ] DIY / DHZ
- [x] Home Owner (This integration is not (fully) functional with a home owner account!)

**Envoy**
- [x] Metered with CTs installed
- [ ] Metered without CTs
- [ ] Standard

- FW version: D8.2.4225 (5eea92)
- Amount of micro inverters connected: 23

**Home Assistant**
- Version: 2024.8.1

**Additional context**
Was working on last HA build from July 2024.
- Upgraded Envoy HACS integration & Upgraded HA to latest. Than issue started with connection from enphase_envoy_installer to envoy
- Removed integration and added from scratch. 
- Envoy IP is automatically detected. After entering credentials I get an "Unexpected Error"
-  I can login to the envoy using the same credentials.

Relevant snippet of Home Assistant error log. 
This error originated from a custom integration.

Logger: custom_components.enphase_envoy.config_flow
Source: custom_components/enphase_envoy/config_flow.py:181
integration: Enphase Envoy (Installer) (documentation, issues)
First occurred: 10:03:28 AM (2 occurrences)
Last logged: 10:10:35 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/enphase_envoy/config_flow.py", line 181, in async_step_user
    envoy_reader = await validate_input(self.hass, user_input)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/enphase_envoy/config_flow.py", line 53, in validate_input
    await envoy_reader.get_data()
  File "/config/custom_components/enphase_envoy/envoy_reader.py", line 1176, in get_data
    await self.init_authentication()
  File "/config/custom_components/enphase_envoy/envoy_reader.py", line 1038, in init_authentication
    await self._get_enphase_token()
  File "/config/custom_components/enphase_envoy/envoy_reader.py", line 971, in _get_enphase_token
    self._token = await self._fetch_owner_token_json()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/enphase_envoy/envoy_reader.py", line 937, in _fetch_owner_token_json
    raise EnlightenError("Could not Authenticate via Enlighten")
custom_components.enphase_envoy.envoy_reader.EnlightenError: Could not Authenticate via Enlighten

**Comment by jeangroen** [comment]
Update: 
After unchecking the box that this is just a home-owner account the login works and the integration seems to be working now.
